#ifndef KVM_API_TEST_H
#define KVM_API_TEST_H


#define KVM_TEST_DMA_MAP_ADDR 0x100
#define KVM_TEST_DMA_MAP_ADDR 0x100
#define KVM_TEST_DMA_MAP_SIZE 0x200
#define KVM_TEST_DMA_UNMAP_ADDR 0x300
#define KVM_TEST_DMA_MAP 0x400
#define KVM_TEST_DMA_UNMAP 0x500

#endif
